server:
  port: 8125

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway

  sleuth:
    sampler:
      probability: 1.0

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: conteiner-service
          uri: lb://conteiner-service
          predicates:
            - Path=/conteiner-service/**
        - id: veiculo-service
          uri: lb://veiculo-service
          predicates:
            - Path=/veiculo-service/**
        - id: cargasolta-service
          uri: lb://cargasolta-service
          predicates:
            - Path=/cargasolta-service/**
        - id: transportadora-service
          uri: lb://transportadora-service
          predicates:
            - Path=/transportadora-service/**
        - id: agendamento-service
          uri: lb://agendamento-service
          predicates:
            - Path=/agendamento-service/**
        - id: openapi
          uri: lb://api-gateway
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs(?<path>.*), /$\{path}/v3/api-docs

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: 'health,prometheus'
  endpoint:
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true