global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "api-agendamento-job"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["agendamento-service:8400"]
        labels:
          application: "api-agendamento"
  - job_name: "api-conteiner-job"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "conteiner-service:8000" ]
        labels:
          application: "api-conteiner"
  - job_name: "api-veiculo-job"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "veiculo-service:8100" ]
        labels:
          application: "api-veiculo"
  - job_name: "api-cargasolta-job"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "cargasolta-service:8200" ]
        labels:
          application: "api-cargasolta"
  - job_name: "api-transportadora-job"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "transportadora-service:8300" ]
        labels:
          application: "api-transportadora"
