name: Continuous Integration with Github

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Setup Java JDK
        uses: actions/setup-java@v3.5.0
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Building Eureka Naming Server Container Image
        working-directory: ./naming-server
        run: mvn spring-boot:build-image -DskipTests
        
      - name: Building API Gateway Container Image
        working-directory: ./api-gateway
        run: mvn spring-boot:build-image -DskipTests
        
      - name: Building Conteiner Microsservice Jar
        working-directory: ./conteiner-service
        run: mvn clean package -DskipTests
        
      - name: Building Veiculo Microsservice Jar
        working-directory: ./veiculo-service
        run: mvn clean package -DskipTests
        
      - name: Building Carga Solta Microsservice Jar
        working-directory: ./cargasolta-service
        run: mvn clean package -DskipTests
      
      - name: Building Transportadora Microsservice Jar
        working-directory: ./transportadora-service
        run: mvn clean package -DskipTests
        
      - name: Building Agendamento Microsservice Jar
        working-directory: ./agendamento-service
        run: mvn clean package -DskipTests
        
      - name: Docker Compose Build
        working-directory: .
        run: docker-compose build
        
      - name: Push to Docker Hub Container Registry
        run:  |
          docker tag ${{ secrets.DOCKER_USERNAME }}/naming-server:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/naming-server:${{ github.run_id }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/naming-server:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/naming-server:latest
          
          docker tag ${{ secrets.DOCKER_USERNAME }}/api-gateway:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/api-gateway:${{ github.run_id }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/api-gateway:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
          
          docker tag ${{ secrets.DOCKER_USERNAME }}/conteiner-service:latest ${{ secrets.DOCKER_USERNAME }}/conteiner-service:${{ github.run_id }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/veiculo-service:latest ${{ secrets.DOCKER_USERNAME }}/veiculo-service:${{ github.run_id }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/cargasolta-service:latest ${{ secrets.DOCKER_USERNAME }}/cargasolta-service:${{ github.run_id }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/transportadora-service:latest ${{ secrets.DOCKER_USERNAME }}/transportadora-service:${{ github.run_id }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/agendamento-service:latest ${{ secrets.DOCKER_USERNAME }}/agendamento-service:${{ github.run_id }}
          
          docker push ${{ secrets.DOCKER_USERNAME }}/naming-server:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/naming-server:latest
          
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
          
          docker push ${{ secrets.DOCKER_USERNAME }}/conteiner-service:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/conteiner-service:latest
          
          docker push ${{ secrets.DOCKER_USERNAME }}/veiculo-service:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/veiculo-service:latest
          
          docker push ${{ secrets.DOCKER_USERNAME }}/cargasolta-service:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/cargasolta-service:latest
          
          docker push ${{ secrets.DOCKER_USERNAME }}/transportadora-service:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/transportadora-service:latest
          
          docker push ${{ secrets.DOCKER_USERNAME }}/agendamento-service:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/agendamento-service:latest
